### ISSUE TITLE
按照md操作，将爱企查cookie设置到config.yaml中依然无法使用

### ISSUE THREAD

**Issue by 1263080327** [wgpsec/ENScan_GO#1]
按照md操作，将爱企查cookie设置到config.yaml中依然无法使用
提示[Error] 没有查询到关键词 “小米” [Fatal] 没有获取到PID

**Comment by linjiananallnt** [comment]
同样的问题

**Comment by apt-kristaps** [comment]
+1

**Comment by Feng4** [comment]
爱企查反爬机制被触发，获取不到pid

**Comment by GZ-ZXL** [comment]
+1

**Comment by keac** [comment]
爱企查似乎是加了个新的验证 aqc_ssr 目前再尝试绕过

**Comment by keac** [comment]
建议使用 -i 在爱企查获得到PID之后进行查询，目前关键词查询API存在异常

**Comment by apt-kristaps** [comment]
> 建议使用 -i 在爱企查获得到PID之后进行查询，目前关键词查询API存在异常

改成无头浏览器的会不会好一点

**Comment by keac** [comment]
问题已修复
