### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by nex121** [wgpsec/ENScan_GO#10]
错误信息如下：

**Comment by nex121** [comment]
goroutine 1 [running]:
github.com/wgpsec/ENScan/internal/tianyancha.getTb(0xc0000b7e00?, 0xc000325080, 0x6?)
        E:/Code/Project/wgpsec/ENScanGo/internal/tianyancha/tianyancha.go:196 +0x64f
github.com/wgpsec/ENScan/internal/tianyancha.getInfoList({0xc00000ca58, 0x8}, 0xc000325080, 0x7d2116?)
        E:/Code/Project/wgpsec/ENScanGo/internal/tianyancha/tianyancha.go:222 +0x2aa
github.com/wgpsec/ENScan/internal/tianyancha.getCompanyInfoById({0xc00000ca58, 0x8}, 0x1, 0x0?, {0x0, 0x0}, {0xc00004abc0, 0x2, 0x43cb1e?}, 0xc0000bd050, ...)
        E:/Code/Project/wgpsec/ENScanGo/internal/tianyancha/tianyancha.go:72 +0xa95
github.com/wgpsec/ENScan/internal/tianyancha.GetEnInfoByPid(0xc0001180f0)
        E:/Code/Project/wgpsec/ENScanGo/internal/tianyancha/tianyancha.go:42 +0x2cb
github.com/wgpsec/ENScan/runner.RunJob(0xc0001180f0)
        E:/Code/Project/wgpsec/ENScanGo/runner/runner.go:65 +0x20a
github.com/wgpsec/ENScan/runner.RunEnumeration(0xc0001180f0)
        E:/Code/Project/wgpsec/ENScanGo/runner/runner.go:30 +0x20a
main.main()
        E:/Code/Project/wgpsec/ENScanGo/enscan.go:12 +0x45

**Comment by nex121** [comment]
所查询公司不便透露 可私聊

**Comment by keac** [comment]
bug问题已知，天眼查bug 下个版本会修复
