### ISSUE TITLE
天眼查使用过快需要手动输入滑块验证码

### ISSUE THREAD

**Issue by Co1t5f0ot** [wgpsec/ENScan_GO#100]
![image](https://github.com/wgpsec/ENScan_GO/assets/78132218/9e56a687-2091-4a9f-a5b6-605dd2fcc06b)
![image](https://github.com/wgpsec/ENScan_GO/assets/78132218/ed3930a7-c5d9-4d9d-be84-c4c8baeeeec4)
![image](https://github.com/wgpsec/ENScan_GO/assets/78132218/3f709058-08a5-4dd4-9c4b-426069a61504)

**Comment by keac** [comment]
后面会增加滑动重试功能，可以尝试添加延时参数解决，详见readme
