### ISSUE TITLE
查询报错

### ISSUE THREAD

**Issue by myqf23** [wgpsec/ENScan_GO#101]
天眼查：ERROR: runtime error: invalid memory address or nil pointer dereference
![image](https://github.com/wgpsec/ENScan_GO/assets/81756571/ca8b81ba-9dab-428b-b6b8-0276d5c1f90c)
企查查：

![image](https://github.com/wgpsec/ENScan_GO/assets/81756571/46055531-45bc-49df-9b1b-af7f07891e14)

**Comment by keac** [comment]
安全验证参考readme过安全验证后贴入完整cookie
