### ISSUE TITLE
查到一半按Ctrl+C退出能否合并已查询的结果

### ISSUE THREAD

**Issue by lovelyjuice** [wgpsec/ENScan_GO#108]
有时候查了一半，弹出百度安全验证，按Ctrl+C退出，之前查询到的结果不会合并
`-f 企业列表.txt -field icp,app,wx_app -invest 51 -type aqc --is-branch --branch -is-merge -o D:\output -hold -deep 4 --is-show`

**Comment by keac** [comment]
计划在下个版本加入实时写入功能

**Comment by keac** [comment]
beta 版本已加入，另外遇到安全验证不用退出，直接过安全验证即可继续查询
