### ISSUE TITLE
查询供应商信息为空

### ISSUE THREAD

**Issue by LL2XX** [wgpsec/ENScan_GO#111]
存在供应商
<img width="674" alt="image" src="https://github.com/wgpsec/ENScan_GO/assets/24318621/f4a5dbd5-086e-4409-b494-1dd78736d7dd">

查询不到
`.\enscan-0.0.17-windows-amd64.exe -i 4450067223 -type tyc -field supplier --supplier`

![image](https://github.com/wgpsec/ENScan_GO/assets/24318621/8035a004-a7fa-418d-81d9-e1174426e18a)

`.\enscan-0.0.18-windows-amd64.exe -i 82990170932082 -type aqc -field supplier --supplier`

<img width="488" alt="image" src="https://github.com/wgpsec/ENScan_GO/assets/24318621/6ef9b2b6-1387-432e-a475-61abec62390f">

**Comment by keac** [comment]
确实存在这个bug，先看看怎么修
