### ISSUE TITLE
用天眼查查询时无法获取投资信息和股东信息

### ISSUE THREAD

**Issue by Kevil-hui** [wgpsec/ENScan_GO#113]
tianyancha: 'HWWAFSESID=2807fb89f*********91047'        # 天眼查   Cookie
  tycid: '2****************7'        		# 天眼查   CApi ID(capi.tianyancha.com)

enscan-0.0.18-windows-amd64.exe -n 爱奇艺 -invest 50 -type tyc
![image](https://github.com/wgpsec/ENScan_GO/assets/43275273/ee0d119f-cb46-4c3f-bdd3-03d94bdb5e53)

**Comment by Lay0us1** [comment]
[INFO] TYC查询 控股企业
[Error] [TYC] getInfoList {"errorCode":0,"isLogin":0,"message":"登录后可查看更多","special":"mustlogin","state":"warn","vipMessage":""}
[INFO] 【TYC】控股企业 数量为空
