### ISSUE TITLE
调用天眼查时，需要滑动验证码。

### ISSUE THREAD

**Issue by hfx96** [wgpsec/ENScan_GO#114]
<img width="779" alt="image" src="https://github.com/wgpsec/ENScan_GO/assets/65392776/55b40015-2abb-480e-816a-181a4af0056b">

<img width="546" alt="image" src="https://github.com/wgpsec/ENScan_GO/assets/65392776/9e4257c9-d423-4c62-8f9a-4ca1c2b691b0">

请问出现这类情况，如何解决。

**Comment by keac** [comment]
按照错误提示滑动验证码后即可继续。有问题清贴上操作过程
