### ISSUE TITLE
请问师傅 是哪里出现了问题 为什么运行之后得不到结果总返回这样的结果

### ISSUE THREAD

**Issue by jacky8lee** [wgpsec/ENScan_GO#115]
![qqq](https://github.com/wgpsec/ENScan_GO/assets/62919907/3f8c7383-3278-4a07-ba55-c1ea37b76bc3)

**Comment by jacky8lee** [comment]
[WRN] 工具仅用于信息收集，请勿用于非法用途
[WRN] 开发人员不承担任何责任，也不对任何滥用或损坏负责.
[DEBUG] DEBUG 模式已开启
[INFO] 关键词:【小米|】数据源：[aqc] 数据字段：[icp weibo wechat app wx_app]
[DEBUG] 【查询错误信息】
<!DOCTYPE html><html><head><meta charset="UTF-8">  <title></title>   <meta name="keywords" content="">   <meta name="description" content="">  <meta http-equiv="X-UA-Compatible" content="IE=edge"><meta http-equiv="content-language" content="zh-CN">         <meta property="og:site_name" content="爱企查">  <meta property="og:type" content="website">       <meta name="google-site-verification" content="5cHddheTrPUV43Sax7vL0alqZq2vDULTVjPf0VnStV4"><link rel="dns-prefetch" href="//ts.bdimg.com"><link rel="dns-prefetch" href="//himg.bdimg.com"><link rel="shortcut icon" href="//xinpub.cdn.bcebos.com/static/favicon.ico" type="image/x-icon"><script type="text/javascript" src="https://dlswbr.baidu.com/heicha/mm/2061/acs-2061.js?_=1715301633"></script><script type="text/javascript" src="//passport.baidu.com/passApi/js/uni_login_wrapper.js"></script> <link href="//xinpub.cdn.bcebos.com/aiqicha/static/1715250260/css/vendors.f728722cdec.css" rel="stylesheet"><link href="//xinpub.cdn.bcebos.com/aiqicha/static/1715250260/css/accessrestriction.f68aa91491f.css" rel="stylesheet"><script src="//xinpub.cdn.bcebos.com/aiqicha/static/1715250260/js/0.308d59ab40f.js"></script>  <script>/* eslint-disable */
        var _hmt = _hmt || [];
        (function() {
            var hm = document.createElement("script");
            hm.src = "https://hm.baidu.com/hm.js?ad52b306e1ae4557f5d3534cce8f8bbf";
            hm.setAttribute('async', 'async');
            hm.setAttribute('defer', 'defer');
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();


        function setCookie(name, value) {
            var Days = 30;
            var exp = new Date();
            exp.setTime(exp.getTime() + Days * 24 * 60 * 60 * 1000);
            document.cookie = name + "=" + escape(value) + ";expires=" + exp.toGMTString() + ";Secure";
        }
        window['__abbaidu_2061_cb'] = function (responseData) {
            var {data, key_id, sign} = JSON.parse(responseData);
            setCookie('_s53_d91_', data);
            setCookie('_j47_ka8_', key_id);
            setCookie('_y18_s21_', sign);
        };

        (function () {
            var shitong = document.createElement("script");
            shitong.src = 'https://dlswbr.baidu.com/heicha/mw/abclite-2061-s.js?v=' + Math.random();
            shitong.setAttribute('async', 'async');
            shitong.setAttribute('defer', 'defer');
            var st = document.getElementsByTagName('script')[0];
            st.parentNode.insertBefore(shitong, st);
            // document.body.appendChild(shitong);
        })();

        /* eslint-enable */</script></head><body><div id="app"></div><script>/* eslint-disable */  window.loginStatus = 0;  window.pageData = {"sid":"","isLogin":0,"userName":null,"casapi":null,"passapi":"\/\/passport.baidu.com\/passApi\/js\/uni_login_wrapper.js","logoutUrl":"\/\/aiqicha.baidu.com\/my\/logout","logintype":0,"userPhoto":"https:\/\/himg.bdimg.com\/sys\/portrait\/item\/default.jpg","homePage":"\/\/aiqicha.baidu.com","passDomain":"https:\/\/passport.baidu.com","queryType":[{"name":"\u5168\u90e8","type":"0","placeholder":"\u8bf7\u8f93\u5165\u60f3\u67e5\u8be2\u7684\u5185\u5bb9","logName":"all"},{"name":"\u4f01\u4e1a\u540d\/\u6ce8\u518c\u53f7","type":"1","placeholder":"\u8f93\u5165\u4f01\u4e1a\u540d\u3001\u6ce8\u518c\u53f7","logName":"enterprise_name"},{"name":"\u6cd5\u4eba\u4ee3\u8868","type":"2","placeholder":"\u8f93\u5165\u6cd5\u4eba\u4ee3\u8868","logName":"legal_represent"},{"name":"\u5730\u5740","type":"3","placeholder":"\u8f93\u5165\u5730\u5740","logName":"address"},{"name":"\u7ecf\u8425\u8303\u56f4","type":"4","placeholder":"\u8f93\u5165\u7ecf\u8425\u8303\u56f4","logName":"scope_business"},{"name":"\u80a1\u4e1c","type":"5","placeholder":"\u8f93\u5165\u80a1\u4e1c","logName":"shareholders"},{"name":"\u9ad8\u7ba1","type":"6","placeholder":"\u8f93\u5165\u9ad8\u7ba1","logName":"main_members"},{"name":"\u5546\u6807","type":"7","placeholder":"\u8f93\u5165\u5546\u6807\u540d\u79f0","logName":"mark"}],"queryWord":"","version":"V1.0.33","mLoginUrl":"https:\/\/wappass.baidu.com\/passport\/login?tpl=zhengxin&authsite=0&overseas=1","mLogoutUrl":"https:\/\/wappass.baidu.com\/passport\/?logout&tpl=zhengxin&u=https%3a%2f%2fxin.baidu.com%2fm","mRegUrl":"https:\/\/wappass.baidu.com\/passport\/reg?tpl=zhengxin&authsite=0&overseas=1&u=https%3a%2f%2fxin.baidu.com%2fm","isGuidesApp":0,"isDisplayEgg":0,"topBarInfo":[{"title":"\u70ed\u95e8\u529f\u80fd","child":[{"name":"\u62db\u6295\u6807\u67e5\u8be2","jumpUrl":"https:\/\/xunbiaobao.baidu.com\/?source=aqc_pc_top_app","imgUrl":"https:\/\/xin-static.cdn.bcebos.com\/aiqicha-pc\/index\/header-application\/applicationbiddingquery.png","isNew":true,"isNeedLogin":false},{"name":"\u6279\u91cf\u53d7\u76ca\u4eba","jumpUrl":"https:\/\/aiqicha.baidu.com\/batchquery?type=benefit","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu-batchbenefit.png","isNew":true,"isNeedLogin":false},{"name":"\u6279\u91cf\u67e5\u8be2","jumpUrl":"https:\/\/aiqicha.baidu.com\/batchquery","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu-plcx.png","isNew":false,"isNeedLogin":false},{"name":"\u4f01\u4e1a\u8ba4\u9886","jumpUrl":"https:\/\/qiye.baidu.com\/usercenter\/claim\/qualify?fr=c1001","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu-rl.png","isNew":false,"isNeedLogin":true},{"name":"\u756a\u756a\u5bfb\u5ba2\u5b9d","jumpUrl":"https:\/\/xunkebao.baidu.com\/index.html#\/?source=pc_app","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu-xkb.png","isNew":false,"isNeedLogin":false},{"name":"\u9ad8\u7ea7\u641c\u7d22","jumpUrl":"https:\/\/aiqicha.baidu.com\/advancesearch","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu-gjss.png","isNew":false,"isNeedLogin":false},{"name":"\u8206\u60c5\u76d1\u6d4b","jumpUrl":"https:\/\/aiqicha.baidu.com\/commercial\/publicopinion?entry=11","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu-yqjc.png","isNew":false,"isNeedLogin":false},{"name":"\u65b0\u4f01\u67e5\u8be2","jumpUrl":"https:\/\/shangjibao.baidu.com\/businessRecommand\/dynamicRecommand?type=0&source=aqcpctopapp","imgUrl":"https:\/\/xinpub.bj.bcebos.com\/aiqicha\/newmenus\/query_comp.png","isNew":true,"isNeedLogin":false},{"name":"\u4f01\u4e1a\u5957\u9910","jumpUrl":"https:\/\/aiqicha.baidu.com\/usercenter\/member?tab=1&entry=2314005","imgUrl":"https:\/\/xinpub.bj.bcebos.com\/aiqicha\/newmenus\/menu-comppackage.png","isNew":true,"isNeedLogin":false}]},{"title":"\u4e13\u9879\u67e5\u8be2","child":[{"name":"\u67e5\u5173\u7cfb","jumpUrl":"https:\/\/aiqicha.baidu.com\/relations\/findrelations?entry=32","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu-cgx.png","isNew":false,"isNeedLogin":false},{"name":"\u67e5\u8001\u8d56","jumpUrl":"https:\/\/aiqicha.baidu.com\/discredit","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu-cll.png","isNew":false,"isNeedLogin":false},{"name":"\u67e5\u5546\u6807","jumpUrl":"https:\/\/aiqicha.baidu.com\/mark","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu-csb.png","isNew":false,"isNeedLogin":false},{"name":"\u5730\u56fe\u67e5\u8be2","jumpUrl":"https:\/\/aiqicha.baidu.com\/map?entry=44","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu-dtcx.png","isNew":false,"isNeedLogin":false},{"name":"\u65b0\u7f51\u5feb\u67e5","jumpUrl":"https:\/\/aiqicha.baidu.com\/icpsearch?entry=21","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu-icpsearch.png","isNew":false,"isNeedLogin":false},{"name":"\u7a7a\u58f3\u626b\u63cf","jumpUrl":"https:\/\/aiqicha.baidu.com\/shellscan\/s","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu_shellscan.png","isNew":true,"isNeedLogin":false},{"name":"\u67e5\u98ce\u9669","jumpUrl":"https:\/\/aiqicha.baidu.com\/riskscan\/s","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu_riskscan.png","isNew":true,"isNeedLogin":false},{"name":"\u627e\u670d\u52a1","jumpUrl":"https:\/\/yiqifu.baidu.com\/?fr=aiqicha_function_services","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu-servicefind.png","isNew":true,"isNeedLogin":false},{"name":"\u516c\u53f8\u6838\u540d","jumpUrl":"https:\/\/yiqifu.baidu.com\/g\/c\/toolforregisteringcompany","imgUrl":"https:\/\/xin-static.cdn.bcebos.com\/aiqicha-pc\/head-menu-icon\/tool-for-company.png","isNew":true,"isNeedLogin":false}]},{"title":"\u4ea7\u54c1\u4e2d\u5fc3","child":[{"name":"\u79ef\u5206\u5546\u57ce","jumpUrl":"https:\/\/qiye.baidu.com\/usercenter\/mall","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu-jfsc.png","isNew":false,"isNeedLogin":true},{"name":"\u5546\u5bb6\u4e2d\u5fc3","jumpUrl":"https:\/\/qiye.baidu.com\/usercenter\/claimlist","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu-sjzx.png","isNew":false,"isNeedLogin":true},{"name":"\u5bfc\u51fa\u8bb0\u5f55","jumpUrl":"https:\/\/qiye.baidu.com\/usercenter\/exportdata","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu-dcjl.png","isNew":false,"isNeedLogin":true},{"name":"\u6211\u7684\u5173\u6ce8","jumpUrl":"https:\/\/qiye.baidu.com\/usercenter\/focus","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu-wdgz.png","isNew":false,"isNeedLogin":true},{"name":"\u6211\u7684\u7ea0\u9519","jumpUrl":"https:\/\/qiye.baidu.com\/usercenter\/correct","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu-wdjc.png","isNew":false,"isNeedLogin":true},{"name":"\u7528\u6237\u53cd\u9988","jumpUrl":"dialog-feedback","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu-yhfk.png","isNew":false,"isNeedLogin":true},{"name":"\u5728\u7ebf\u54a8\u8be2","jumpUrl":"dialog-feedback","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu-zixun.png","isNew":true,"isNeedLogin":true}]},{"title":"\u8ba4\u8bc1\u6743\u76ca","child":[{"name":"\u5a92\u4f53\u5408\u4f5c","jumpUrl":"https:\/\/aiqicha.baidu.com\/audit\/media","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu-mthz.png","isNew":true,"isNeedLogin":true},{"name":"\u5b66\u751f\u4e13\u4eab","jumpUrl":"https:\/\/aiqicha.baidu.com\/audit\/student","imgUrl":"https:\/\/xinpub.cdn.bcebos.com\/aiqicha\/newmenus\/menu-xszx.png","isNew":true,"isNeedLogin":true},{"name":"\u8eab\u4efd\u8ba4\u8bc1","jumpUrl":"https:\/\/qiye.baidu.com\/usercenter\/authenticationcenter","imgUrl":"https:\/\/xin-static.bj.bcebos.com\/ixinnest\/mycenter\/AuthenticationCenter\/authentication.png","isNew":true,"isNeedLogin":true}]}]};
        window.isSpider = null;
        window.updateTime = null;

        if (window.pageData.result.isDidiwei) {
            window.location.href = `/login?u=${encodeURIComponent(window.location.href)}`
        }

        /* eslint-enable */</script><script data-app="eyJhcHBfa2V5IjoiNTY0NyIsImFwcF92aWV3IjoicHJvbW90ZSIsImJyb3dzZXJfdXJsIjoiaHR0cHM6Ly9zb2ZpcmUuYmFpZHUuY29tL2RhdGEvdWEvYWIuanNvbiIsImZvcm1fZGVzYyI6IiIsInNlbmRfaW50ZXJ2YWwiOjUwLCJzZW5kX21ldGhvZCI6M30=" src="//sofire.bdstatic.com/js/xaf.js"></script><script>try {
            var initParams = {
                "aid": "5647",
                "a": '',
                "c": "",
                "app": "universe",
                "ver": "",
            }
            xaf.init(initParams);
        } catch(e) {
            console.log(e);
        }</script><script>    window._supportWebp = false;
        (function() {
            var img = new Image();
            function getResult(event) {
                window._supportWebp = event && event.type === 'load' ? img.width == 1 : false;
            }
            img.onerror = getResult;
            img.onload = getResult;
            img.src = 'data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoBAAEAAwA0JaQAA3AA/vuUAAA=';
        })();</script> <script src="//xinpub.cdn.bcebos.com/aiqicha/static/1715250260/js/accessrestriction.6991799c9be.js"></script> </body></html>

**Comment by keac** [comment]
@jacky8lee 请正确配置cookie

**Comment by jacky8lee** [comment]
![www](https://github.com/wgpsec/ENScan_GO/assets/62919907/f83ad061-051c-49f7-a31c-69a3fb087f79)
![yyy](https://github.com/wgpsec/ENScan_GO/assets/62919907/f97be6d7-4fc6-4571-8b19-c56bad9d743a)

**Comment by jacky8lee** [comment]
![yyy](https://github.com/wgpsec/ENScan_GO/assets/62919907/4223786b-96bc-43ae-bfa3-bb8e085c321c)
![www](https://github.com/wgpsec/ENScan_GO/assets/62919907/25d8a526-203a-4a48-b1d6-e8e571500088)
