### ISSUE TITLE
频繁触发需要滑块验证，有没有好的解决办法

### ISSUE THREAD

**Issue by iBesokuse** [wgpsec/ENScan_GO#121]
我已经设置了延时参数5秒的间隔查询，但是仍然频繁的触发滑块验证，对我需要批量跑公司的控股公司有很大的影响。请问一下有没有好的解决办法，谢谢！

**Comment by keac** [comment]
可以尝试挂代理的方式~

**Comment by rick-ccc** [comment]
挂代理没用啊,挨个都试了一遍
