### ISSUE TITLE
你好，请问下企查查目前还是不能用吗？

### ISSUE THREAD

**Issue by lyer530** [wgpsec/ENScan_GO#122]
你好，请问下企查查目前还是不能用吗？配置文件里填了cookie和tid，运行时还是报错，debug也没有其他提示
<img width="158" alt="image" src="https://github.com/wgpsec/ENScan_GO/assets/48832828/54789de4-c0f9-4849-9fb5-3632fc78369d">

**Comment by keac** [comment]
你好，因涉及到签名算法问题，企查查仅供团队内部使用，不开源。下个版本将优化下错误提示，感谢支持
