### ISSUE TITLE
--email参数未定义 

### ISSUE THREAD

**Issue by c0mpl1ng** [wgpsec/ENScan_GO#123]
github说可以提取邮箱信息，但是加了参数提示未定义。

<img width="919" alt="image" src="https://github.com/wgpsec/ENScan_GO/assets/52808596/a011ff7e-4168-4b00-8a74-283213a84619">

<img width="910" alt="image" src="https://github.com/wgpsec/ENScan_GO/assets/52808596/591a48fc-386e-432c-9386-d683c340e0b7">

**Comment by keac** [comment]
已删除说明
