### ISSUE TITLE
-type qcc 报错

### ISSUE THREAD

**Issue by ice0x** [wgpsec/ENScan_GO#124]
cookie已经设置好了的，aqc是正常的
![image](https://github.com/wgpsec/ENScan_GO/assets/171759904/93fcd59e-d4b1-4e04-89d1-4a6deb153d89)

**Comment by ice0x** [comment]
![image](https://github.com/wgpsec/ENScan_GO/assets/171759904/06f5271c-4a34-4c32-81cc-b0af199ef5b1)

**Comment by keac** [comment]
qcc未公开使用 请使用aqc、tyc
