### ISSUE TITLE
小蓝本获取的token用不了，并且默认的爱qi查跳转链接会显示非法请求

### ISSUE THREAD

**Issue by coder-ljj555** [wgpsec/ENScan_GO#126]
小蓝本的token是直接 cookie里面那个参数 token: .........................后面....这部分吗，我这里显示不成功，会出错。爱企查就是链接跳转到非法请求

**Comment by kuang-zy** [comment]
我也是 爱企查疯狂报错

**Comment by keac** [comment]
建议挂上burp代理尝试，绕过非浏览器识别
