### ISSUE TITLE
只有爱企查，天眼查可用

### ISSUE THREAD

**Issue by loseyourself1** [wgpsec/ENScan_GO#133]
![image](https://github.com/user-attachments/assets/2debfb41-5c59-484d-a985-26b1cff386e5)
![image](https://github.com/user-attachments/assets/afdd992a-e180-4ba4-ad2b-62167bab88e1)
其他的方式会报错，请问应该如何解决这个问题？

**Comment by keac** [comment]
目前仅可使用tyc、aqc，其他的接口可以使用旧版本
