### ISSUE TITLE
ICP备案查询建议使用百度商机宝的API，爱企查的API会有遗漏

### ISSUE THREAD

**Issue by lovelyjuice** [wgpsec/ENScan_GO#139]
![image](https://github.com/user-attachments/assets/0fe241aa-3ab7-42d5-b63b-0d1ea38f7c98)
![image](https://github.com/user-attachments/assets/a2b6a8f8-0fb5-4eed-b389-ab10deff17d2)

爱企查的API是：https://aiqicha.baidu.com/detail/icpinfoAjax?pid=
商机宝API为：https://shangjibao.baidu.com/crm/web/sjb/toker/queryenterpriserecommendlistwithicpinfo

**Comment by lovelyjuice** [comment]
这几天又对更多目标测试了下，发现商机宝也会漏域名，比爱企查漏的更多

**Comment by keac** [comment]
ICP备案后期正在考虑加入 https://github.com/HG-ha/ICP_Query 的支持
