### ISSUE TITLE
新功能提议 ，配置文件热加载，以便于随时更换被标记非法的AQCcookie

### ISSUE THREAD

**Issue by Crazy-FuQing** [wgpsec/ENScan_GO#150]
具体实现，大约 当需要打开链接进行验证的时候提示用户进行更换cookie而不用中断进程
![image](https://github.com/user-attachments/assets/367692bb-7199-4e9c-8bad-267a54300676)
![image](https://github.com/user-attachments/assets/c0770f65-ebd3-4933-b3e3-a367e7569c2d)

**Comment by keac** [comment]
无需关闭程序，打开爱企查尝试搜索任意关键词，**保持cookie不变（和浏览器的一致）** 即可触发安全验证 验证过后就可以直接继续了

**Comment by keac** [comment]
如果触发不了一般都是已经关闭了浏览器，也就是和配置文件里的cookie不一致~ 实测批量查询的时候把浏览器开着不关，可以正常触发安全验证，验证通过程序10秒就会自动继续，不会中断，如果还有问题请打开。

**Comment by Crazy-FuQing** [comment]
感谢k哥回复 这边的问题是在浏览器中进行验证后会直接回显非法请求

![image](https://github.com/user-attachments/assets/940d9edc-92c0-421c-8c01-073655aab4cf)
![image](https://github.com/user-attachments/assets/9eeef247-eaf9-4d8b-ae82-c193c88255cc)

**Comment by keac** [comment]
这个浏览器直接打开接口肯定会提示，已在程序中优化提示
