### ISSUE TITLE
aqc显示出现错误

### ISSUE THREAD

**Issue by 0user-liang** [wgpsec/ENScan_GO#156]
![image](https://github.com/user-attachments/assets/953db61b-9445-4dff-9617-bb466bcb3564)

**Comment by 0user-liang** [comment]
<img width="523" alt="微信图片_20241226101725" src="https://github.com/user-attachments/assets/e6a7a764-7eb8-4a95-b529-03030651451a" />

**Comment by keac** [comment]
请附上版本号 debug信息

**Comment by 0user-liang** [comment]
版本enscan-v1.0.2-windows-amd64
![image](https://github.com/user-attachments/assets/3a61b657-f9f5-4792-96f8-f04f32fdb4bf)

**Comment by keac** [comment]
请使用 --debug 参数 详细提交一下 下面应该有报错信息的位置

**Comment by keac** [comment]
已知问题，请更新最新版
