### ISSUE TITLE
需求：简洁模式输出域名信息

### ISSUE THREAD

**Issue by Shea-Des** [wgpsec/ENScan_GO#16]
增加只输出域名信息的功能

**Comment by keac** [comment]
师傅可以试试 ./ENScanPublic_amd64_linux -n 小米  -field icp 只查询icp备案到表格中

**Comment by Shea-Des** [comment]
好的，我试试

**Comment by keac** [comment]
如批量查询时，可以进行合并导出结果 --is-merge
