### ISSUE TITLE
天眼查获取不到网站信息

### ISSUE THREAD

**Issue by G0rdita** [wgpsec/ENScan_GO#17]
使用-field icp -type tyc无法获取天眼查的网站信息
<img width="570" alt="image" src="https://user-images.githubusercontent.com/40414497/183792485-435272a4-3f33-4c57-be52-3181827d1e6b.png">
天眼查官网确实是有备案信息的
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/40414497/183792635-4bbf6a7d-0736-46c6-8a5d-6b3e551d8672.png">

**Comment by keac** [comment]
感谢师傅反馈，天眼查存在严重BUG，下个版本会修复

**Comment by keac** [comment]
0.0.5版本已修复
