### ISSUE TITLE
天眼查查数据有问题

### ISSUE THREAD

**Issue by admin-del** [wgpsec/ENScan_GO#21]
![1](https://user-images.githubusercontent.com/105182827/188255805-166454c1-db22-45d5-9d7c-868fab90529e.png)
![2](https://user-images.githubusercontent.com/105182827/188255807-6d7839b9-4994-45d6-be2d-073a7ffd7eb3.png)

**Comment by keac** [comment]
感谢师傅反馈，应该是返回结果的问题，看看这个bug怎么解决

**Comment by keac** [comment]
感谢师傅反馈，看下来是使用的关键词推荐的接口，会出现这样的问题，接下来替换为关键词搜索接口应该就没问题了
