### ISSUE TITLE
登录之后获取cookie查询出来的结果还是带*

### ISSUE THREAD

**Issue by sunr0e** [wgpsec/ENScan_GO#23]
![image](https://user-images.githubusercontent.com/40360053/190301409-c829f7c0-8c8f-4dde-b930-0c2713418df5.png)
![image](https://user-images.githubusercontent.com/40360053/190301482-d12bdec7-7756-49ae-b6ac-f96f46a45cbd.png)
![Uploading image.png…]()

**Comment by sunr0e** [comment]
![image](https://user-images.githubusercontent.com/40360053/190301871-54e7540d-e243-4e4c-8294-280279118f0e.png)

**Comment by sunr0e** [comment]
![image](https://user-images.githubusercontent.com/40360053/190302016-9b8ab27a-5077-4dce-b625-6ad6807c8107.png)

**Comment by keac** [comment]
![image](https://user-images.githubusercontent.com/16091665/190898405-1c0860d4-b959-4f48-97e4-8a49114ae4cf.png)

师傅，根据本地复测没有复现这个问题，建议检查下是不是少复制了Cookie信息
