### ISSUE TITLE
关于指针报错的问题

### ISSUE THREAD

**Issue by jielansudo** [wgpsec/ENScan_GO#24]
当导出数据过大时，会报[Error] [QCC] ERROR: runtime error: invalid memory address or nil pointer dereference%，可以把结果实时存储在文件中吗，而不是结束的时候在一起存储。

**Comment by keac** [comment]
感谢师傅反馈，目前是全部放在一起导出存储，可以看看怎么实现实时存下来

**Comment by Dido1960** [comment]
使用如下命令查询百分百投资信息以及控股公司时
`./ENScan -n 小米  -invest 100 -hold`
发生运行时错误：
[Error] [QCC] ERROR: runtime error: invalid memory address or nil pointer dereference%
<img width="769" alt="EC4EA664-7E37-480C-B600-3EC393B3F2E7" src="https://user-images.githubusercontent.com/44106495/195991087-440af4ec-f975-4e3c-bac0-f3bc64336a44.png">


无法正常导出数据，而且提示“需要登陆才能查询控股公司”
但此时配置了爱企查cookie，可以正常查看邮箱信息

<img width="913" alt="14F4462B-E944-4F6B-99D9-93E0162F6986" src="https://user-images.githubusercontent.com/44106495/195991037-9cd2ec28-a9d7-433c-a6cf-1c48f4c4b4a8.png">

**Comment by keac** [comment]
感谢师傅反馈 我复现下看看这个bug问题在哪
