### ISSUE TITLE
天眼查报错-登录后可查看更多

### ISSUE THREAD

**Issue by nu0l** [wgpsec/ENScan_GO#27]
```
[Error] [TYC] getInfoList {"errorCode":0,"isLogin":0,"message":"登录后可查看更多","special":"mustlogin","state":"warn","vipMessage":""}
```
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/54735907/197442531-0d0909a2-9ff8-4188-91fb-a97834f5ce42.png">

**Comment by keac** [comment]
替换为登陆的cookie试试呢，看看是不是少复制东西了，尽量不要使用 `document.cookie` 查看cookie，有些cookie是http only 可能会少复制

**Comment by lovelyjuice** [comment]
抓包发现`X-Auth-Token`的值和Cookie中的jwt对不上，而且只有`https://capi.tianyancha.com/`开头的请求会出现这种问题。jwt的签名竟然是1，在burp中用天眼查cookie中的auth_token值替换错误的jwt就可以了

![image](https://user-images.githubusercontent.com/20644461/233838177-d1ec06ca-65fe-4f50-aed4-f48e3afed48d.png)
