### ISSUE TITLE
建议将查询结果的website统一提取

### ISSUE THREAD

**Issue by AdminTest0** [wgpsec/ENScan_GO#3]
.\ENScanPublic_amd64_windows.exe -f keywords.txt   #查询指定多家投资公司

每个主体都会单独生成一个xlsx文件，如果想汇总URL、IP等就需要一个一个打开复制粘贴，用notepad++处理结果也很麻烦

![a6fe1622c3e147447439be9e6d140f2](https://user-images.githubusercontent.com/33925462/159212386-be54a317-5d18-4ef6-8176-04c157f4cbe2.png)

ENScan的python版本是会把website提取到test.txt

![a4ebf0a8f8eddd46e6178723645f908](https://user-images.githubusercontent.com/33925462/159212774-a54e92bf-432f-4834-8439-2d3c150d6ef0.png)

所以建议将查询结果的website统一提取，（notepad++处理后的格式是：网站名称 域名）

**Comment by keac** [comment]
PD-0.0.3版本已支持
