### ISSUE TITLE
readme中使用支持API和配置文件中有一处不一致

### ISSUE THREAD

**Issue by ybdt** [wgpsec/ENScan_GO#37]
readme中使用支持API和配置文件中有一处不一致，readme中是酷安市场，配置文件中是小蓝本
<img width="385" alt="image" src="https://user-images.githubusercontent.com/65813455/201043718-84a63edb-8ccd-4a2c-a157-29def9aad1c6.png">
<img width="135" alt="image" src="https://user-images.githubusercontent.com/65813455/201043800-7d6318ec-de38-4b6a-b192-720866973427.png">

**Comment by keac** [comment]
感谢师傅反馈，酷安市场无需配置cookie信息，所以在配置文件中没有显示
