### ISSUE TITLE
【天眼查】当企业不存在时会报错退出

### ISSUE THREAD

**Issue by MoarStya** [wgpsec/ENScan_GO#48]
![image](https://user-images.githubusercontent.com/95091700/221413652-9302bedc-3895-4061-9efe-196adad315f7.png)

**Comment by MoarStya** [comment]
enscan.exe -n xxx公司 -deep 3 -invest 70 -type tyc

**Comment by keac** [comment]
无法复现bug，请提供下搜索关键词
