### ISSUE TITLE
API 模式 消费者无法消费队列

### ISSUE THREAD

**Issue by r00tuser111** [wgpsec/ENScan_GO#52]
使用API模式进行部署，并注册了一个消费者，但是没有数据。

API 启动命令：
```
go run enscan.go -config config.yaml -api -debug
```
client 启动命令：
```
go run enscan.go -config config.yaml -client task -debug
```

添加一个搜索小米公司：
```
POST /api/info

orgname=%E5%B0%8F%E7%B1%B3%E7%A7%91%E6%8A%80%E6%9C%89%E9%99%90%E8%B4%A3%E4%BB%BB%E5%85%AC%E5%8F%B8&branch=false&update=true
```

API 日志如下:
<img width="972" alt="image" src="https://user-images.githubusercontent.com/22544959/228779913-382cc227-91b3-468c-90df-c3c6106c8372.png">

但这个任务貌似没有处理。

client和API端都没有打印：任务接受成功。

**Comment by keac** [comment]
请使用 -client tasks 目前该参数为固定状态
![image](https://user-images.githubusercontent.com/16091665/228781632-f97a1259-3215-4cd8-87d1-59c66123bb68.png)
