### ISSUE TITLE
现在可以支持查询所有企业吗？

### ISSUE THREAD

**Issue by leveryd** [wgpsec/ENScan_GO#53]
<img width="499" alt="image" src="https://user-images.githubusercontent.com/1846319/231391295-533540e6-09b3-4931-9561-4e2a6039a6f3.png">

从程序运行信息看到"默认选择第一个企业"，那查询所有企业，是需要我先把PID导出到文件，然后 `-f pid.txt`来查吗？还是有更简单的方式？

**Comment by keac** [comment]
这种查询情况建议梳理下对应公司的关系信息，是属于子公司、分公司、对外投资的公司，然后再使用enscan快速进行梳理
