### ISSUE TITLE
qcc提示签名未更新

### ISSUE THREAD

**Issue by magic-rookie** [wgpsec/ENScan_GO#54]
配置文件中已经配置qcc 相关cookie
![image](https://user-images.githubusercontent.com/86155731/232179893-2be21f11-a3af-4f21-8ce6-685910cc3167.png)
运行提示qcc签名未更新，无法使用
![image](https://user-images.githubusercontent.com/86155731/232179922-0a5fae1c-f109-46a6-91ce-ad23cad01f50.png)

**Comment by JacHeiuang** [comment]
没人维护吗
