### ISSUE TITLE
aldzs查询开发的相关小程序失败

### ISSUE THREAD

**Issue by 1205747671** [wgpsec/ENScan_GO#65]
`[INFO] 查询  开发的相关小程序 【默认取100个】
[Error] 【aldzs】似乎出了点问题 请您先进行登录在查看相关数据`

查询关键词 XXX 的小程序 成功，但是开发的相关小程序就失败了。
cookie也配了，是刚手机注册登录之后获取到的cookie。

**Comment by keac** [comment]
用的是请求的token 不是cookie哈
