### ISSUE TITLE
新版本“没有获取到PID”

### ISSUE THREAD

**Issue by log0ff** [wgpsec/ENScan_GO#66]
Version: 0.0.12

                https://github.com/wgpsec/ENScan

[WRN] 工具仅用于信息收集，请勿用于非法用途
[WRN] 开发人员不承担任何责任，也不对任何滥用或损坏负责.
[INFO] 关键词:【xxx】数据源：[aqc] 数据字段：[icp weibo wechat app wx_app]
[Error] 没有查询到关键词 “xxx”
[Error] 没有获取到PID

**Comment by zhxknb1** [comment]
<img width="657" alt="image" src="https://github.com/wgpsec/ENScan_GO/assets/59738277/ce8f621d-e65c-40d1-a356-80525454b15e">

**Comment by zhxknb1** [comment]
<img width="657" alt="image" src="https://github.com/wgpsec/ENScan_GO/assets/59738277/0c7188c7-77c8-46ec-981b-b773b673a605">

**Comment by keac** [comment]
请问搜索的关键词是什么呢，另外指定的渠道是哪个，在网站上能否搜到

**Comment by keac** [comment]
天*查已fix，请在请求的时候挂上burp代理即可正常打开
