### ISSUE TITLE
天眼查接口报错 找不到公司id

### ISSUE THREAD

**Issue by ultramanbu-320** [wgpsec/ENScan_GO#68]
网页405错误 Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon Jul 17 17:39:51 CST 2023
There was an unexpected error (type=Method Not Allowed, status=405).

**Comment by ultramanbu-320** [comment]
修复后的程序好像会报错”[TYC] COOKIE检查失效，请检查COOKIE是否正确！“

**Comment by ultramanbu-320** [comment]
bean.go 下GetReqReturnPage

**Comment by ultramanbu-320** [comment]
[Error] [TYC] COOKIE检查失效，请检查COOKIE是否正确！
[Error] [TYC] ERROR: runtime error: invalid memory address or nil pointer dereference

**Comment by keac** [comment]
加上Cookie了嘛，必须要登陆的
