### ISSUE TITLE
v13天眼查又报错了吗?

### ISSUE THREAD

**Issue by ultramanbu-320** [wgpsec/ENScan_GO#69]
[Error] 没有查询到关键词 “小米” [Error] 没有获取到PID

**Comment by ultramanbu-320** [comment]
挂burp后，同样无法获取网页数据： https://capi.tianyancha.com/cloud-tempest/web/searchCompanyV3 ，网页显示：{"errorCode":302004,"isLogin":0,"message":"mustlogin","special":"","state":"warn","vipMessage":""}

**Comment by keac** [comment]
加上Cookie了嘛

**Comment by ultramanbu-320** [comment]
都加上了，天眼查一直跑不通。
