### ISSUE TITLE
天眼查报错

### ISSUE THREAD

**Issue by Burden-xy** [wgpsec/ENScan_GO#75]
[Error] 【TYC】未知错误 %!s(int=429)
[Error] [TYC] ERROR: runtime error: invalid memory address or nil pointer dereference
好像是因为查询次数比较多，导致被风控，需要输入滑动验证码

**Comment by keac** [comment]
@Burden-xy 请开启 --debug 贴下详细的配置，检查下自己配置是否正确

**Comment by Burden-xy** [comment]
> @Burden-xy 请开启 --debug 贴下详细的配置，检查下自己配置是否正确

配置没问题，手动登录天眼查然后输入下滑动验证码就解决了
