### ISSUE TITLE
[Error] [TYC] COOKIE检查失效，请检查COOKIE是否正确！ [Error] [TYC] ERROR: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 0xf7i** [wgpsec/ENScan_GO#79]
已经登录，多次检查cookie与tycid，尝试了代理，还是这个问题
![image](https://github.com/wgpsec/ENScan_GO/assets/105481923/c2822fc0-28cd-4099-8faa-ba0ba73345a0)

**Comment by keac** [comment]
--deubg 看下报错详情

**Comment by 0xf7i** [comment]
其实已经加了
![image](https://github.com/wgpsec/ENScan_GO/assets/105481923/23b4edd5-176c-4805-a13b-d30c031456c7)

**Comment by keac** [comment]
COOKIE 是获取到哪里的呢，这边看了下代码 在提示 “请输入中国大陆手机号” 时 说明没有登陆。建议师傅可以挂burp代理抓包看下具体响应的请求包，方便排查问题

**Comment by keac** [comment]
在本地测试是没有问题的，建议在f12 network获取完整的Cookie尝试，console出来的可能会因为http only 失去部分关键信息

**Comment by 0xf7i** [comment]
cookie 是获取的autotoken这部分，抓包好像是这个包出的问题，给强制跳转到登录页面
![image](https://github.com/wgpsec/ENScan_GO/assets/105481923/2400b266-9ae1-4aed-8b9c-f431d736e5d7)

**Comment by 0xf7i** [comment]
使用完整的cookie，就可以了，谢谢师傅

**Comment by jky-yy** [comment]
你们的cookie 是怎么获取的，我用auth_token 和 tycid 也是相同报错.
