### ISSUE TITLE
查询遗漏问题

### ISSUE THREAD

**Issue by DaYuanzhang** [wgpsec/ENScan_GO#8]
`ENScanPublic_amd64_windows_v0.0.3.exe -n 中国民生银行股份有限公司 -invest-num 50`
我这里用这条命令查股权50以上的企业，以下是查询结果
![image](https://user-images.githubusercontent.com/67625626/167080273-5e82a266-3e7e-4ada-953e-0e13633faa9d.png)
这里看到民生金融公司
![image](https://user-images.githubusercontent.com/67625626/167080392-1028223d-19b7-4ba5-bf79-f9a9742e77df.png)
查询该公司的备案域名
![image](https://user-images.githubusercontent.com/67625626/167080484-97cc131e-4019-4215-9ac4-9fb6b366d1e2.png)
是能够查到有备案域名的，但是使用工具没有查到
![image](https://user-images.githubusercontent.com/67625626/167080549-ae5b3e38-4f20-4a3f-a5d0-1b4d9d322e38.png)
同样的命令 我在查其他公司的时候是能够覆盖到底下子公司的备案域名的，但是这里不行，可以问下这是什么原因吗

**Comment by FishM4n** [comment]
同样的问题

**Comment by keac** [comment]
投资比例计算bug 下个版本会fix
