### ISSUE TITLE
[Error] 没有查询到关键词 “小米” 

### ISSUE THREAD

**Issue by DjiangLiu** [wgpsec/ENScan_GO#80]
[Error] 没有查询到关键词 “小米” 
[Error] 没有获取到PID

**Comment by hello-ltem** [comment]
前两天还能用，

**Comment by keac** [comment]
@hello-ltem 哥们，贴下参数 开启 --debug 看报错 啥也没有看不出问题

**Comment by hello-ltem** [comment]
@keac  报错，
![image](https://github.com/wgpsec/ENScan_GO/assets/59221123/7b189f7c-f463-4cad-9b9f-9b22645d041a)
![image](https://github.com/wgpsec/ENScan_GO/assets/59221123/e8adf84a-3743-4ffd-b662-fd2ae862a81d)

**Comment by hello-ltem** [comment]
无报错。。

**Comment by hello-ltem** [comment]
已添加API

**Comment by keac** [comment]
@hello-ltem 检查是否能正常打开网站，cookie是否配置正确

**Comment by Not-my** [comment]
同样的问题，网站正常打开，cookie正确 用的天眼查的cookie

**Comment by keac** [comment]
![image](https://github.com/wgpsec/ENScan_GO/assets/16091665/17f1d1cb-c257-4bb3-b94c-0e2608139e36)
可能是IP被拉黑了 看下是否有验证

**Comment by keac** [comment]
> 同样的问题，网站正常打开，cookie正确 用的天眼查的cookie

天眼查测试没有问题，检查Cookie和id是否配置正确
