### ISSUE TITLE
爱企查校验referer机制更改

### ISSUE THREAD

**Issue by imkitsch** [wgpsec/ENScan_GO#82]
爱企查referer头为https://aifanfan.baidu.com/时302
![1](https://github.com/wgpsec/ENScan_GO/assets/61683826/dce00e62-5c3c-4e4f-8582-4046fd1ef433)

修改为https://aiqicha.baidu.com/后正常查询

**Comment by keac** [comment]
经测试有随机性，有时候正常查几下就能正常使用，师傅可以再测试测试试试，欢迎提交PR

**Comment by keac** [comment]
已更新
