### ISSUE TITLE
少了一个veryvp

### ISSUE THREAD

**Issue by ifacker** [wgpsec/ENScan_GO#83]
![image](https://github.com/wgpsec/ENScan_GO/assets/26481367/fa83c197-b719-4423-b940-998e2ea14b79)
![image](https://github.com/wgpsec/ENScan_GO/assets/26481367/b155cef2-15c3-4db4-8769-2a451728d62b)

**Comment by hi-unc1e** [comment]
我看了一下你说的这个“veryvp选项不存在的问题”问题——问题的确存在，难以解决。

## 原因
- veryvp 的网站完全不能访问，接口已经失效；我个人推测是跑路了。
![image](https://github.com/wgpsec/ENScan_GO/assets/67778054/3aa19fc0-e0cd-45f0-bbc1-4dd06385082d)

```
https://www.17ce.com/site/http/20240217_8471c840cd9311ee8793ffe35d67e381:1.html
https://www.17ce.com/site/http/20240217_4e1803a0cd9211ee8793ffe35d67e381:1.html
```
- 弃用 veryvp，不仅涉及到修改 `config.go`里的`ScanTypeKeys`，还涉及其他功能，需要在veryvp.go选用合适的函数（目前有的几个貌似都不对）

**Comment by keac** [comment]
--email 即可启用，但是目前接口失效了 后面会去掉
