### ISSUE TITLE
天眼查企业不存在时报错退出程序

### ISSUE THREAD

**Issue by mntn0x** [wgpsec/ENScan_GO#86]
![image](https://github.com/wgpsec/ENScan_GO/assets/26903390/01187ab0-58d0-4221-96f8-c8e500b4415a)
命令：./enscan-0.0.15-darwin-arm64 -n 中国电信集团有限公司 -invest 100 -deep 2 -type all -field icp
场景：查询深度为2时，如果企业在投资版图里有，但查询企业时为404，会直接报错退出

**Comment by keac** [comment]
下个版本会修复该问题
