### ISSUE TITLE
tyc在进行大于51%控股公司、供应商、分支机构，只要ICP备案信息，并且批量获取邮箱信息查询提示需要登录

### ISSUE THREAD

**Issue by githubb000** [wgpsec/ENScan_GO#88]
执行./enscan -n 唐人神集团股份有限公司 -field icp --hold --supplier --branch  报错，相关的cookie,tycid以进行配置，但还是提示需要登录
![image](https://github.com/wgpsec/ENScan_GO/assets/135519887/fc3c5cc0-14c3-4b6a-a412-dc1f61c93dd1)
![image](https://github.com/wgpsec/ENScan_GO/assets/135519887/57c2f6d1-bb88-48f7-8cf3-216ae966d0a3)

**Comment by ST0new** [comment]
遇到了同样的问题。其他配置和上面的一样
![image](https://github.com/wgpsec/ENScan_GO/assets/45659593/02eb793a-c49f-434a-84e3-6f85bc0910ac)

**Comment by keac** [comment]
网页看查询也需要vip
