### ISSUE TITLE
需求：增加疑似控股企业的信息收集

### ISSUE THREAD

**Issue by 245915834** [wgpsec/ENScan_GO#9]
企业子公司的真实信息范围收集不够，许多真实子公司在疑似控股企业内，例如爱企查中的数据
![image](https://user-images.githubusercontent.com/89074745/168787476-985a88de-112c-4582-b08f-e5089a4861ed.png)

**Comment by 245915834** [comment]
可参考另一个项目
https://github.com/SiJiDo/IEyes

**Comment by keac** [comment]
请使用参数 --invest-rd 来查询不确定控股比例的公司，如果还有问题请重新开启此issue
