### ISSUE TITLE
新增需求：批量筛选准确的备案名称

### ISSUE THREAD

**Issue by qaz7791869** [wgpsec/ENScan_GO#90]
用户手中拿到几十上百家单位名称，但是不一定是准确的备案名称 ，用enscan可以批量对指定文件中的备案信息进行初步查询，筛选出未100%命中的备案单位名称，然后这些没准确命中的告诉给用户  用户自己手动去找完整备案名称
输出样例如下：
```
未准确命中的备案：
xxx
xxx
xxxxx
xxxxx

准确命中的备案：
xxxxx
xxx
xxx
xxx

```

**Comment by keac** [comment]
enscan主要是用来收集企业关联信息以及资产信息，这个功能不考虑添加
