### ISSUE TITLE
请问大佬这是啥问题.啥也查询不到?

### ISSUE THREAD

**Issue by daymissed** [wgpsec/ENScan_GO#94]
![image](https://github.com/wgpsec/ENScan_GO/assets/62062283/c6a87fd3-494d-4231-8306-531fac4ee276)

**Comment by wwwziziyu** [comment]
t同样的问题，每次都是百度安全验证，等大佬回答

**Comment by keac** [comment]
打开爱企查，然后过了安全验证复制全部cookie也是一样吗

**Comment by keac** [comment]
本地测试看起来都是正常的
![image](https://github.com/wgpsec/ENScan_GO/assets/16091665/4d19a7e3-2043-4488-a51f-35b46a4621a3)

**Comment by keac** [comment]
各位师傅注意下 请用 https://aiqicha.baidu.com 的cookie，请不要用 https://www.aiqicha.com 的cookie 两个不一样！

**Comment by GG-o1** [comment]
走个代理，换个IP就好了
