### ISSUE TITLE
Enscan_go的cookie选择问题

### ISSUE THREAD

**Issue by qingsmoke** [wgpsec/ENScan_GO#96]
大师傅，enscan_go是不是只能接收到爱企查的cookie啊？我配置天眼查、七麦数据、站长之家的cookie压根就不用。
![1705375261829](https://github.com/wgpsec/ENScan_GO/assets/106363133/b451ec5a-9fa3-4699-966e-50c64999d3bd)
![image](https://github.com/wgpsec/ENScan_GO/assets/106363133/e17d2409-aec2-4245-8b7f-92b0ce8d438a)

**Comment by keac** [comment]
按照你设置的type调用的，详细看readme

**Comment by qingsmoke** [comment]
原来如此，没注意*这个细节，感谢感谢
